### ISSUE TITLE
fails with react-templates 0.5.4

### ISSUE THREAD

**Issue by caeus** [AlexanderPavlenko/react-templates-loader#15]
Can't believe I started using react-templates a couple of hours before they released 0.5.3 and 0.5.4 (yes, both almost simultaneously)
At some point it started failing with;
`Module build failed: RTCodeError: Line 1: Unexpected token =`
And at the end I discovered that the default module system in 0.5.2 was "amd" and the default module system in 0.5.3+ is "none". With that system it fails because the "name" option is not provided by webpack. and so it renders something like `var = function(){bla bla bla render function}`
To fix it, the loader should be now 
`{test: /\.rt$/, loader:"react-templates?modules=amd"}`
So yep, you could change the documentation

**Comment by konyu** [comment]
This problem also occurs in  version 0.5.3

**Comment by steezeburger** [comment]
Any idea how to get es6 modules working? I get the same errors using es6.

**Comment by kdojeteri** [comment]
+1 please update the docs.

**Comment by electic** [comment]
In the latest RC.4 version of webpack, this will not work since webpack requires a -loader postfix It should be:

`{ 
      test: /\.rt$/, 
      exclude: /node_modules/,
      loader: "react-templates-loader" 
    }`
