### ISSUE TITLE
Support react-templates 0.6.1

### ISSUE THREAD

**Issue by motin** [AlexanderPavlenko/react-templates-loader#18]
I installed react-templates and got 0.6.1 by default, then installed react-templates-loader and got 0.5.1. Had no luck getting that combination to work (got "Cannot find module" upon each attempt to require a .rt-file, and the webpack cli would complain with "ERROR in Unexpected token {"). 

Had to install react-templates 0.5.4 to get it to work:

yarn add react-templates@0.5.4

**Comment by AlexanderPavlenko** [comment]
react-templates-loader 0.6.1 released
