### ISSUE TITLE
Broken by react-templates 0.6.2

### ISSUE THREAD

**Issue by lsglick** [AlexanderPavlenko/react-templates-loader#25]
react-templates 0.6.2 no longer includes the `/src` directory:
https://github.com/wix/react-templates/commit/140ede94c7e8f8bb8f41b0c74cdacda7e5e28d89#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R33

That makes these imports no longer resolve:
https://github.com/AlexanderPavlenko/react-templates-loader/blob/a62a70f64c86d2d41231dee0cf066842813d46bf/index.js#L1

**Comment by AlexanderPavlenko** [comment]
Thanks! Released as v0.6.5
